config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :videos
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def show
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(video_params)
    @video.save
    redirect_to video_path(@video)# Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    redirect_to video_path(@video)
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to video_path(@video), status: :see_other
  end

  private

  def video_params
    params.require(:video).permit(:title, :category, :published_year)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProyect180123</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with model: @video do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :published_year %>
  <%= f.number_field :published_year%>
  <%= f.submit %>
<% end %>

app/views/videos/edit.html.erb
<h1>edit</h1>

<%= render "videos/form", videos: @videos %>
<%= link_to "Back to all videos", videos_path %>

app/views/videos/index.html.erb
<h1>Todos los Videos</h1>

<ul>
  <% @videos.each do |video| %>
    <li> <%= video.title %></li>
    <li> <%= video.category %></li>
    <li> <%= video.published_year %></li>
  <% end  %>
</ul>

app/views/videos/new.html.erb
 <h1> Create Video </h1>

<%= render "videos/form", videos: @videos %>
<%= link_to "Back to all videos", videos_path %>

app/views/videos/show.html.erb
<h1>info:</h1>

<h2> Video title: <%= @video.title %> </h2>
<p> Video Cathegory: <%= @video.category  %></p>
<p> Published_year: <%= @video.published_year %></p>

<%= link_to "delete",
  video_path(@video),
  data: {turbo_method: :delete, turbo_confirm:"seguro?"}
%>